### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by gugakatsi** [Nikaoto/Shamen#1]
# UI
- [x] Mana regen and mana costs
- [x] Character UI drawing
- [x] Totem icons and 0.5s cooldown!
- [x] **Welcome screen**
 
# Gameplay
- [x] Map totem controls to joysticks
- [x] Remove random totem generator
- [ ] ~Expand totem areal on each stack~

# Visuals
- [x] Bright blue background
- [ ] Moving clouds in background
- [x] Player sprites
- [x] Totem sprites
